format_version: 3
pipelines:
  ops-base:
    group: platform
    label_template: "${git[:8]}"
    materials:
      git:
        git: "git@github.com:kudulab/ops-base.git"
        branch: master
        destination: ops-base
      releaser:
        git: git@github.com:kudulab/releaser.git
        destination: releaser
      docker_ops:
        git: git@github.com:kudulab/docker-ops.git
        destination: docker-ops
      secret_ops:
        git: git@github.com:kudulab/secret-ops.git
        destination: secret-ops
    stages:
      - test:
          secure_variables:
            VAULT_TOKEN: "AES:CcHDC55m7VB+vEYF8cQkww==:f9Ea93sVJNpmqxTRX/2BxHqhkU3M/5hkgbyDURfLcXQ="
          clean_workspace: true
          jobs:
            ubuntu16:
              resources:
                - docker
              tasks:
               - exec:
                  working_directory: ops-base
                  command: /bin/bash
                  arguments:
                    - -c
                    - "./tasks.sh build ubuntu16"
               - exec:
                  working_directory: ops-base
                  command: /bin/bash
                  arguments:
                    - -c
                    - "./tasks.sh test ubuntu16"
               - exec:
                  working_directory: ops-base
                  command: /bin/bash
                  arguments:
                    - -c
                    - "./tasks.sh itest ubuntu16 releaser"
               - exec:
                  working_directory: ops-base
                  command: /bin/bash
                  arguments:
                    - -c
                    - "./tasks.sh itest ubuntu16 docker-ops"
               - exec:
                  working_directory: ops-base
                  command: /bin/bash
                  arguments:
                    - -c
                    - "./tasks.sh itest ubuntu16 secret-ops"
               - exec:
                  working_directory: ops-base
                  command: /bin/bash
                  arguments:
                    - -c
                    - "./tasks.sh build_gui ubuntu16"
      - release:
          clean_workspace: true
          jobs:
            code:
              resources:
                - docker
              tasks:
               - exec:
                  working_directory: ops-base
                  command: /bin/bash
                  arguments:
                    - -c
                    - "./tasks.sh release"
